# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: MkPolaris
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Darmarj
site_description: >-
  One branded static site from a set of Markdown files to host the documentation for Open Source or Commercial project

# Repository
repo_name: darmarj/MkPolaris
repo_url: https://github.com/darmarj/MkPolaris

# Copyright
copyright: Copyright &copy; .2020 ~ 2024. Darmarj.M

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mas.to/@hydenzw
    - icon: fontawesome/brands/github
      link: https://github.com/darmarj
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/kenzzw

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - DevOps:
      - Container Runtime:
          - Containerd: DevOps/Container/containerd.md
          - Docker: DevOps/Docker/docker.md
          - Namespace: DevOps/Container/namespace.md
          - Cgroups: DevOps/Container/cgroups.md
          - Nerdctl: DevOps/Container/nerdctl.md
      - Terraform:
          - Kubernetes: DevOps/Terraform/Kubernetes.md
          - KVM: DevOps/Terraform/KVM.md
          - Proxmox: DevOps/Terraform/Proxmox.md
      - Rancher:
          - K3s: DevOps/Rancher/K3s.md
      - Kubernetes:
          - Architecture: DevOps/Kubernetes/architecture.md
          - Kubernetes: DevOps/Kubernetes/kubernetes.md
  - GNU/Linux:
      # - Kernel:
      - Network: Linux/Network/NetCat.md
      # - Shell Script:
      - Distro:
          - Gentoo:
              - Installation:
                  - Linux/Gentoo/Introduction.md
                  - Linux/Gentoo/Media.md
                  - Linux/Gentoo/Network.md
                  - Linux/Gentoo/Prepare the disks.md
                  - Linux/Gentoo/Stage3.md
                  - Linux/Gentoo/Base system.md
                  - Linux/Gentoo/Kernel.md
                  - Linux/Gentoo/System.md
                  - Linux/Gentoo/Tools.md
                  - Linux/Gentoo/Bootloader.md

  - Blog:
      - blog/index.md
