authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
  darmarj:
    name: Darmarj M
    description: Owner
    avatar: https://avatars.githubusercontent.com/u/94155500
    url: https://github.com/darmarj
